#  Slicing

Slicing in Python allows for extracting portions of arrays (including multi-dimensional ones) using a concise syntax. Here's a breakdown with

## 1. Basic Slicing
* **array[start:end]** extracts elements from start (inclusive) to end (exclusive).
* **array[start:]**  extracts elements from start to the end.
* **array[:end]**  extracts elements from the beginning to end (exclusive).
* **array[:]**  creates a copy of the entire array.
* **array[start:end:step]**  extracts elements with a specified step.

## 2. Multi-Dimensional Slicing
* **For a 2D array (matrix),**  the syntax is array[row_slice, col_slice].
* **array[row_start:row_end,**  col_start:col_end] extracts a submatrix.
* **array[row_index, :]**  extracts all columns for a specific row.
* **array[:, col_index]**  extracts all rows for a specific column.

In [2]:
import numpy as np

## String 

In [5]:
    my_string = "Hello, World!"
    print(my_string[7:])  # Output: World!
    print(my_string[:5])  # Output: Hello
    print(my_string[::2]) # Output: Hlo ol!

World!
Hello
Hlo ol!


## Slice Function

In [7]:
    my_slice = slice(1, 5, 2)
    my_list = [10, 20, 30, 40, 50, 60]
    print(my_list[my_slice]) # Output: [20, 40]

[20, 40]


## 1D Array

In [6]:
    my_list = [1, 2, 3, 4, 5, 6]
    print(my_list[1:4])  # Output: [2, 3, 4]
    print(my_list[::2])  # Output: [1, 3, 5]
    print(my_list[::-1]) # Output: [6, 5, 4, 3, 2, 1]

[2, 3, 4]
[1, 3, 5]
[6, 5, 4, 3, 2, 1]


## 1D Array

In [9]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr_1d[2:5])   # Output: [3 4 5]
print(arr_1d[:4])   # Output: [1 2 3 4]
print(arr_1d[5:])   # Output: [6 7 8 9]
print(arr_1d[1:8:2])  # Output: [2 4 6 8]

[3 4 5]
[1 2 3 4]
[6 7 8 9]
[2 4 6 8]


## 2D Array

In [10]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[0:2, 1:3]) # Output: [[2 3] [5 6]]
print(arr_2d[1, :])    # Output: [4 5 6]
print(arr_2d[:, 2])    # Output: [3 6 9]

[[2 3]
 [5 6]]
[4 5 6]
[3 6 9]


## 2D Array

In [17]:
arr_3 = np.array([[0, 1, 2, 3, 4, 5], [6, 7, 8,9, 10, 11], [12, 13, 14, 15, 16,17],[18,19,20,21,22,23]])

print( arr_3[0:3,1:3])

[[ 1  2]
 [ 7  8]
 [13 14]]


## Explanation Traingle:

* triangle is usually a 2D NumPy array (or similar data structure).
* triangle[:, 1] selects all rows (:), but only the second column (1 since Python uses zero-based indexing).
    
## Typical Name:

* If triangle contains points (like in 2D geometry), columns might represent coordinates:
 - triangle[:, 0] — the x-coordinates of the triangle’s vertices.
 - triangle[:, 1] — the y-coordinates of the triangle’s vertices.
     
## So:

* triangle[:, 1] is commonly called the "y-coordinates" (or "y values") of the triangle’s vertices.

In [3]:
triangle = np.array([[0, 1], [2, 3], [4, 5]])
x_coords = triangle[:, 0]  # x-coordinates of the vertices
y_coords = triangle[:, 1]  # y-coordinates of the vertices


print('Triangle' + str(triangle) ) 

print ('X:' + str(x_coords))
print ('Y:' + str(y_coords) )

Triangle[[0 1]
 [2 3]
 [4 5]]
X:[0 2 4]
Y:[1 3 5]


# [Python Deep Dives Context](./README.md)